version: '3.8'

services:
  postgres:
    image: bitnami/postgresql
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sushi
    # volumes:
      # - ./db/data:/bitnami/postgresql/data
    restart: always
   
  # redis:
  #   image: redis/redis-stack:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   restart: always
    

  sushi-backend:
    image: breeze5690/sushi-backend:v1
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - LOG_LEVEL=Debug
      - JWT_SECRET=secret123
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=sushi
      - MIGRATE_DB=true

      # OAuth Configuration
      - GOOGLE_CLIENT_ID=188782029541-mp3dho0iq7tvjqmnptbha1t30i61lji0.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_REDIRECT_URL=http://localhost:8080/api/v1/auth/callback

      - GITHUB_CLIENT_ID=Ov23lilhxa9zph0EhMjE
      - GITHUB_CLIENT_SECRET=4398d6cf674b60cbaca1ec21a4a730e0985f4ec9
      - GITHUB_REDIRECT_URL=http://localhost:8080/api/v1/auth/callback 

      - FITBIT_CLIENT_ID=23PKSG
      - FITBIT_CLIENT_SECRET=0ba8328d12924c03b89bd0cb23b90e1d
      - FITBIT_REDIRECT_URL=http://localhost:8080/api/v1/auth/callback 
    # volumes:
    #   - ./static:/app/static
    depends_on:
      - postgres
    restart: always
